-- ResolveX Supabase schema
-- Run this file in the Supabase SQL editor.

create extension if not exists pgcrypto;

create table if not exists public.merchants (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  zone_id text not null,
  address text not null,
  lat double precision not null,
  lng double precision not null,
  avg_prep_minutes integer not null,
  created_at timestamptz not null default now()
);

create table if not exists public.riders (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  phone text not null,
  vehicle text not null check (vehicle in ('bike', 'scooter', 'car')),
  zone_id text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.customers (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  email text not null unique,
  phone text not null,
  address text not null,
  lat double precision not null,
  lng double precision not null,
  zone_id text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.orders (
  id uuid primary key default gen_random_uuid(),
  merchant_id uuid not null references public.merchants(id),
  rider_id uuid references public.riders(id),
  customer_id uuid not null references public.customers(id),
  zone_id text not null,
  items jsonb not null,
  status text not null check (status in (
    'placed', 'preparing', 'ready', 'picked_up', 'dropped_off', 'completed', 'cancelled'
  )),
  promised_prep_minutes integer not null,
  promised_delivery_minutes integer not null,
  placed_at timestamptz not null,
  prep_started_at timestamptz,
  ready_at timestamptz,
  picked_up_at timestamptz,
  dropped_off_at timestamptz,
  is_late_flagged boolean not null default false,
  created_at timestamptz not null default now()
);

create index if not exists orders_zone_status_idx on public.orders(zone_id, status);
create index if not exists orders_rider_id_idx on public.orders(rider_id);
create index if not exists orders_merchant_id_idx on public.orders(merchant_id);

create table if not exists public.rider_gps_points (
  id bigint generated by default as identity primary key,
  order_id uuid not null references public.orders(id) on delete cascade,
  rider_id uuid not null references public.riders(id),
  lat double precision not null,
  lng double precision not null,
  speed_kmh double precision,
  recorded_at timestamptz not null
);

create index if not exists rider_gps_points_order_recorded_idx
  on public.rider_gps_points(order_id, recorded_at);

create table if not exists public.refund_history (
  id uuid primary key default gen_random_uuid(),
  customer_id uuid not null references public.customers(id),
  order_id uuid references public.orders(id),
  reason text not null check (reason in ('late', 'wrong_item', 'damaged', 'missing_item', 'other')),
  amount numeric not null,
  outcome text not null check (outcome in ('approved', 'denied', 'voucher')),
  created_at timestamptz not null default now()
);

create table if not exists public.complaints (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null references public.orders(id),
  customer_id uuid not null references public.customers(id),
  type text not null check (type in ('late', 'wrong_item', 'damaged', 'missing_item')),
  description text,
  photo_url text,
  created_at timestamptz not null default now()
);

create table if not exists public.cases (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null references public.orders(id),
  complaint_id uuid references public.complaints(id),
  trigger text not null check (trigger in ('customer_complaint', 'live_feed_late', 'zone_delay')),
  case_payload jsonb not null,
  status text not null default 'open' check (status in ('open', 'checks_running', 'aggregated', 'resolved')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists cases_order_id_idx on public.cases(order_id);
create index if not exists cases_status_idx on public.cases(status);

create table if not exists public.check_results (
  id uuid primary key default gen_random_uuid(),
  case_id uuid not null references public.cases(id) on delete cascade,
  check_name text not null check (check_name in ('photo', 'timing', 'rider_route', 'zone', 'claim_history')),
  result jsonb not null,
  flagged boolean not null,
  created_at timestamptz not null default now()
);

create index if not exists check_results_case_id_idx on public.check_results(case_id);

create table if not exists public.verdicts (
  id uuid primary key default gen_random_uuid(),
  case_id uuid not null unique references public.cases(id) on delete cascade,
  claim_valid boolean not null,
  fault_party text not null check (fault_party in ('merchant', 'rider', 'neither', 'customer_abuse')),
  confidence numeric not null check (confidence >= 0 and confidence <= 1),
  outcome text not null check (outcome in ('NEED_MORE_INFO', 'AUTO_REFUND', 'ZONE_BROADCAST', 'SUPPORT_TICKET')),
  reasons jsonb not null,
  raw_llm_response jsonb not null,
  created_at timestamptz not null default now()
);

create table if not exists public.support_tickets (
  id uuid primary key default gen_random_uuid(),
  case_id uuid not null references public.cases(id) on delete cascade,
  assigned_agent text,
  status text not null default 'open' check (status in ('open', 'in_progress', 'resolved')),
  resolution_notes text,
  created_at timestamptz not null default now(),
  resolved_at timestamptz
);

create index if not exists support_tickets_status_idx on public.support_tickets(status);

create or replace function public.set_cases_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists cases_set_updated_at on public.cases;
create trigger cases_set_updated_at
before update on public.cases
for each row execute function public.set_cases_updated_at();

-- The frontend uploads complaint images to this public demo bucket.
insert into storage.buckets (id, name, public)
values ('complaint-photos', 'complaint-photos', true)
on conflict (id) do update set public = excluded.public;

-- Register tables used by the live dashboards with Supabase Realtime.
do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'orders'
  ) then
    alter publication supabase_realtime add table public.orders;
  end if;
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'rider_gps_points'
  ) then
    alter publication supabase_realtime add table public.rider_gps_points;
  end if;
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'cases'
  ) then
    alter publication supabase_realtime add table public.cases;
  end if;
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'verdicts'
  ) then
    alter publication supabase_realtime add table public.verdicts;
  end if;
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'support_tickets'
  ) then
    alter publication supabase_realtime add table public.support_tickets;
  end if;
end;
$$;

create or replace view public.open_order_positions as
select
  o.id,
  o.zone_id,
  o.status,
  o.is_late_flagged,
  coalesce(g.lat, m.lat) as lat,
  coalesce(g.lng, m.lng) as lng
from public.orders o
join public.merchants m on m.id = o.merchant_id
left join lateral (
  select lat, lng
  from public.rider_gps_points
  where order_id = o.id
  order by recorded_at desc
  limit 1
) g on true
where o.status in ('placed', 'preparing', 'ready', 'picked_up');
