import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { api } from '../lib/api';
const labels={placed:'Awaiting restaurant approval',preparing:'Preparing your food',ready:'Packed and ready',picked_up:'With your rider',dropped_off:'Delivered',completed:'Completed',cancelled:'Declined by restaurant'};
export default function OrderDashboard({mode='customer'}){
 const [orders,setOrders]=useState([]),[riders,setRiders]=useState([]),[selected,setSelected]=useState({}),[error,setError]=useState(''),[busy,setBusy]=useState(false),[tracking,setTracking]=useState(null);
 const load=()=>api('/commerce/orders').then(setOrders).catch(e=>setError(e.message));
 useEffect(()=>{load();const timer=setInterval(load,10000);if(mode==='merchant')api('/commerce/riders').then(setRiders).catch(e=>setError(e.message));return()=>clearInterval(timer);},[mode]);
 useEffect(()=>{if(!tracking)return;let pending=false;const id=navigator.geolocation.watchPosition(async p=>{if(pending)return;pending=true;try{await api(`/commerce/orders/${tracking}/position`,{lat:p.coords.latitude,lng:p.coords.longitude,speed_kmh:Math.max(0,(p.coords.speed||0)*3.6)});}catch(e){setError(e.message);setTracking(null);}finally{pending=false;}},e=>{setError(e.message);setTracking(null);},{enableHighAccuracy:true,maximumAge:10000});return()=>navigator.geolocation.clearWatch(id);},[tracking]);
 async function act(order,action){setBusy(true);setError('');try{let location={};if(action==='deliver'){location=await new Promise((resolve,reject)=>navigator.geolocation.getCurrentPosition(p=>resolve({lat:p.coords.latitude,lng:p.coords.longitude}),()=>reject(new Error('Allow location access to record delivery.')),{enableHighAccuracy:true}));}await api(`/commerce/orders/${order.id}/stage`,{action,...location,...(action==='handover'?{rider_id:selected[order.id]}:{})});if(action==='deliver')setTracking(null);await load();}catch(e){setError(e.message);}finally{setBusy(false);}}
 return <div className="max-w-6xl mx-auto p-6 space-y-5"><div className="flex flex-wrap justify-between gap-3"><div><h1 className="text-2xl font-bold">{mode==='merchant'?'Restaurant orders':mode==='rider'?'Rider deliveries':'My orders'}</h1><p className="text-slate-500">{mode==='merchant'?'Approve, prepare, pack, and hand over each order.':mode==='rider'?'Track your assigned deliveries and confirm each drop-off.':'Track your food from the kitchen to your door.'}</p></div>{mode==='customer'&&<Link to="/" className="btn">Order again</Link>}{mode==='merchant'&&<Link to="/partner" className="btn-secondary">Claims & disputes</Link>}</div>{error&&<p role="alert" className="bg-red-50 text-red-800 rounded p-3">{error}</p>}{!orders.length&&<div className="border rounded-xl bg-white p-8 text-slate-500">No orders yet. New orders will appear here automatically.</div>}
 <div className="grid md:grid-cols-2 gap-5">{orders.map(o=>{const delivery=o.items[0]?.delivery;return <article key={o.id} className="rounded-xl border bg-white p-5 space-y-4"><div className="flex justify-between gap-2"><h2 className="font-bold">Order {o.id.slice(0,8).toUpperCase()}</h2><span className="text-sm rounded bg-emerald-50 text-emerald-800 px-2 py-1">{labels[o.status]||o.status}</span></div><p className="text-xs text-slate-500">{new Date(o.placed_at).toLocaleString()} · Estimated {o.promised_delivery_minutes} minutes</p><ul className="text-sm space-y-1">{o.items.map((item,i)=><li key={i} className="flex justify-between"><span>{item.qty} × {item.name}</span><span>LKR {(item.qty*item.price).toLocaleString()}</span></li>)}</ul><p className="font-bold">Total: LKR {o.items.reduce((s,i)=>s+i.qty*i.price,0).toLocaleString()}</p>{delivery&&<div className="text-sm bg-slate-50 rounded p-3"><p>{delivery.address}</p><p>{delivery.phone}</p><p>{delivery.instructions}</p>{mode==='rider'&&<a target="_blank" rel="noreferrer" className="underline" href={`https://www.google.com/maps/dir/?api=1&destination=${delivery.lat},${delivery.lng}`}>Open delivery directions</a>}</div>}
 <div className="flex gap-2 flex-wrap text-xs">{[['prep_started_at','Accepted'],['ready_at','Packed'],['picked_up_at','Picked up'],['dropped_off_at','Delivered']].map(([key,label])=><span key={key} className={o[key]?'text-emerald-700':'text-slate-400'}>{label}{o[key]?` ${new Date(o[key]).toLocaleTimeString()}`:' · pending'}</span>)}</div>
 {mode==='customer'&&<div className="flex flex-wrap gap-3"><Link to={`/report?order=${o.id}`} className="btn-secondary">Report a problem</Link>{o.case_ids?.map(id=><Link key={id} className="underline text-sm self-center" to={`/report?case=${id}`}>View claim {id.slice(0,6)}</Link>)}</div>}
 {mode==='merchant'&&<div className="flex gap-2 flex-wrap">{o.status==='placed'&&<><button className="btn" disabled={busy} onClick={()=>act(o,'accept')}>Approve & start preparing</button><button className="btn-secondary" disabled={busy} onClick={()=>act(o,'reject')}>Decline</button></>}{o.status==='preparing'&&<button className="btn" disabled={busy} onClick={()=>act(o,'pack')}>Mark packed</button>}{o.status==='ready'&&<><select aria-label="Assign rider" className="field" value={selected[o.id]||''} onChange={e=>setSelected({...selected,[o.id]:e.target.value})}><option value="">Select rider</option>{riders.map(r=><option key={r.id} value={r.id}>{r.name} · {r.vehicle}</option>)}</select><button className="btn" disabled={busy||!selected[o.id]} onClick={()=>act(o,'handover')}>Hand over to rider</button></>}</div>}
 {mode==='rider'&&o.status==='picked_up'&&<div className="flex flex-wrap gap-2"><button className="btn-secondary" onClick={()=>{if(!navigator.geolocation){setError('Location is not supported in this browser.');return;}setTracking(tracking===o.id?null:o.id);}}>{tracking===o.id?'Stop sharing location':'Share live location'}</button><button disabled={busy} className="btn" onClick={()=>act(o,'deliver')}>Confirm delivery</button></div>}
 </article>;})}</div></div>;
}
