import { useEffect, useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { useAuth } from '../auth/AuthContext';
import { api } from '../lib/api';

export default function Storefront() {
 const {user,role}=useAuth(),navigate=useNavigate();
 const [catalog,setCatalog]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const [basket,setBasket]=useState(()=>{try{return JSON.parse(localStorage.getItem('resolvex-basket')) || {merchant:'',items:{}};}catch{return {merchant:'',items:{}};}});
 const [address,setAddress]=useState(''),[phone,setPhone]=useState(''),[lat,setLat]=useState(''),[lng,setLng]=useState(''),[instructions,setInstructions]=useState('');
 const [requestId,setRequestId]=useState(null);
 useEffect(()=>{api('/commerce/catalog').then(setCatalog).catch(e=>setError(e.message));},[]);
 useEffect(()=>{localStorage.setItem('resolvex-basket',JSON.stringify(basket));setRequestId(null);},[basket]);
 const products=catalog?.products ?? [],total=products.reduce((sum,p)=>sum+p.price*(basket.items[p.id]||0),0);
 function quantity(id,change){setBasket(b=>({...b,items:{...b.items,[id]:Math.max(0,Math.min(20,(b.items[id]||0)+change))}}));}
 function locate(){if(!navigator.geolocation){setError('Location is unavailable. Enter the coordinates below.');return;}navigator.geolocation.getCurrentPosition(p=>{setLat(p.coords.latitude.toFixed(6));setLng(p.coords.longitude.toFixed(6));},()=>setError('Location permission was not granted. Enter your delivery coordinates below.'));}
 async function place(e){e.preventDefault();if(!user){navigate('/login',{state:{from:'/'}});return;}if(role!=='customer'){setError('Sign in with a customer account to place an order.');return;}setBusy(true);setError('');const id=requestId||crypto.randomUUID();setRequestId(id);
 try{await api('/commerce/orders',{request_id:id,merchant_id:basket.merchant,items:Object.entries(basket.items).filter(([,qty])=>qty>0).map(([product_id,qty])=>({product_id,qty})),address,phone,lat:Number(lat),lng:Number(lng),instructions});setBasket({merchant:basket.merchant,items:{}});navigate('/my-orders');}catch(e){setError(e.message);}finally{setBusy(false);}}
 return <div className="max-w-7xl mx-auto px-5 py-8 space-y-8">
  <section className="rounded-3xl bg-slate-900 text-white p-8 md:p-12 grid md:grid-cols-2 gap-8 items-center"><div><p className="text-emerald-300 font-semibold text-sm tracking-widest uppercase">ResolveX delivery</p><h1 className="text-4xl md:text-5xl font-bold mt-4 leading-tight">Good food.<br/>Every step accounted for.</h1><p className="text-slate-300 mt-5 max-w-md">Pick your favourites, follow your delivery, and get help with any order — all in one place.</p><div className="flex gap-3 mt-6"><a href="#menu" className="rounded-lg bg-emerald-400 text-slate-900 px-5 py-3 font-semibold">Explore the menu</a>{!user&&<Link to="/signup" className="rounded-lg border border-slate-500 px-5 py-3">Create an account</Link>}</div></div><div className="rounded-2xl bg-white/10 p-8"><div className="text-8xl text-center" aria-hidden="true">🍛</div><p className="text-center mt-5 font-semibold text-xl">Made nearby. Delivered with care.</p><div className="grid grid-cols-3 gap-3 text-center mt-6 text-sm"><span>Freshly<br/>prepared</span><span>Track every<br/>stage</span><span>Support when<br/>you need it</span></div></div></section>
  {error&&<p role="alert" className="rounded-lg bg-red-50 p-4 text-red-800">{error}</p>}
  <div className="grid lg:grid-cols-3 gap-7" id="menu"><section className="lg:col-span-2 space-y-5"><div><h2 className="text-2xl font-bold">What are you craving?</h2><p className="text-slate-500">Demo menu · prices in LKR. Orders are simulated; no payment is collected.</p></div>
   <label className="block font-medium">Choose a restaurant<select className="field mt-2" value={basket.merchant} onChange={e=>setBasket({merchant:e.target.value,items:{}})}><option value="">Select restaurant</option>{catalog?.merchants.map(m=><option key={m.id} value={m.id}>{m.name} · {m.avg_prep_minutes} min prep</option>)}</select></label>
   {!catalog&&<p>Loading menu…</p>}<div className="grid sm:grid-cols-2 gap-4">{products.map(p=><article key={p.id} className="rounded-2xl border bg-white p-5"><div className="bg-orange-50 rounded-xl p-6 text-center text-6xl" aria-hidden="true">{p.emoji}</div><p className="mt-4 text-xs uppercase text-slate-500">{p.category}</p><h3 className="font-semibold text-lg">{p.name}</h3><div className="flex items-center justify-between mt-4"><b>LKR {p.price.toLocaleString()}</b><button className="btn" disabled={!basket.merchant} onClick={()=>quantity(p.id,1)}>Add to basket</button></div></article>)}</div>
  </section><aside className="rounded-2xl border bg-white p-6 h-fit lg:sticky lg:top-4"><h2 className="text-xl font-bold">Your basket</h2>{!total&&<p className="text-slate-500 my-4">Choose a restaurant and add something delicious.</p>}{products.filter(p=>basket.items[p.id]>0).map(p=><div key={p.id} className="border-b py-4"><p className="font-medium">{p.name}</p><div className="flex justify-between items-center mt-2"><div className="flex items-center gap-3"><button aria-label={`Remove one ${p.name}`} className="btn-secondary" onClick={()=>quantity(p.id,-1)}>−</button><span>{basket.items[p.id]}</span><button aria-label={`Add one ${p.name}`} className="btn-secondary" onClick={()=>quantity(p.id,1)}>+</button></div><span>LKR {(p.price*basket.items[p.id]).toLocaleString()}</span></div></div>)}<p className="flex justify-between font-bold py-4"><span>Total</span><span>LKR {total.toLocaleString()}</span></p>
   {total>0&&<form onSubmit={place} className="space-y-3"><h3 className="font-semibold">Delivery details</h3><label className="block text-sm">Street address<textarea required minLength={8} className="field" value={address} onChange={e=>setAddress(e.target.value)}/></label><label className="block text-sm">Contact number<input required minLength={7} className="field" type="tel" value={phone} onChange={e=>setPhone(e.target.value)}/></label><button type="button" className="text-sm underline" onClick={locate}>Use my current location</button><p className="text-xs text-slate-500">Delivery coordinates help your rider find the address.</p><div className="grid grid-cols-2 gap-2"><label className="text-sm">Latitude<input required type="number" min="-90" max="90" step="any" className="field" value={lat} onChange={e=>setLat(e.target.value)}/></label><label className="text-sm">Longitude<input required type="number" min="-180" max="180" step="any" className="field" value={lng} onChange={e=>setLng(e.target.value)}/></label></div><label className="block text-sm">Delivery instructions<input className="field" value={instructions} onChange={e=>setInstructions(e.target.value)}/></label><button className="btn w-full" disabled={busy}>{busy?'Placing order…':user?'Place demo order':'Sign in to order'}</button></form>}
  </aside></div>
 </div>;
}
